const data = [
  {
    id: 'lLeep8',
    showId: null,
    username: null,
    name: '狄仁杰',
    sex: 'MALE',
    avatar:
      'https://staff-avatars-dev.oss-cn-beijing.aliyuncs.com/6145ed4b-5c6d-4427-ad95-2cfed213a2a1',
    title: 'CHIEF_PHYSICIAN',
    departmentName: '测试科室',
    tel: '17740000041',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'NORMAL',
    inviteStatus: 'CONFIRMED',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: '8PgYMb',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lLDxv6',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8VA6Jm',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rwEe3B',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'l93bKV',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8gMwPp',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'l1gLpV',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rq3jyD',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lOMkPq',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5bJVOM',
        price: '10',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: '5A6qzJ',
        price: '8',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '8KDxky',
        price: '10',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: '8VA6JR',
        price: '8',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 7,
  },
  {
    id: '5ZKL7r',
    showId: null,
    username: null,
    name: '韩中睿test07',
    sex: 'MALE',
    avatar: null,
    title: 'ATTENDING_PHYSICIAN',
    departmentName: null,
    tel: '17600000007',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'TO_REVIEW',
    inviteStatus: 'WAITING',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: 'r6yeXO',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'ljWZDQ',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8VA4Vm',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'lLDzY6',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '8Pg3Wb',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8gML2p',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'l93GQV',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rwEbYB',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lOM4yq',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rq3ZKD',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'l1gaEV',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '5bJdnM',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: '5A6eLJ',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: '5Am7J5',
    showId: null,
    username: null,
    name: '陈奕迅',
    sex: 'MALE',
    avatar: '',
    title: 'ATTENDING_PHYSICIAN',
    departmentName: '测试科室',
    tel: '18311114444',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'NORMAL',
    inviteStatus: 'CONFIRMED',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: 'lGELM5',
        price: '1111',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '5RYE38',
        price: '666',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lMGqE5',
        price: '399',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'ldL9Nl',
        price: '111',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '8Ne1Wl',
        price: '66',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rePwQ5',
        price: '39',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8nKaK5',
        price: '222',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rYzeVl',
        price: '133',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8XyGd5',
        price: '79',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8mAkn8',
        price: '111',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'l3poD8',
        price: '88',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '5xdnm5',
        price: '56',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'lQXk4r',
        price: '44',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 1,
  },
  {
    id: '8go7P8',
    showId: null,
    username: null,
    name: '神经1',
    sex: 'MALE',
    avatar:
      'https://staff-avatars-dev.oss-cn-beijing.aliyuncs.com/aca66d92-73f3-4c58-beb2-631ce45d22b0',
    title: 'RESIDENT_PHYSICIAN',
    departmentName: '测试科室',
    tel: '18903719017',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'NORMAL',
    inviteStatus: 'CONFIRMED',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: '5xj07l',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lQQZ6l',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8y37Br',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rzxZX8',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '8W2jdl',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rpRxJ8',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5BkXWr',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'r2vO2r',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '50Z9Yl',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '57PKOr',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: '5ZZwj5',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: 'rJdzv8',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'lvYBqr',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 1,
  },
  {
    id: '5ZKAAr',
    showId: null,
    username: null,
    name: '陈欧',
    sex: 'MALE',
    avatar: null,
    title: 'ATTENDING_PHYSICIAN',
    departmentName: '人a发发恩爱',
    tel: '18311112222',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'NORMAL',
    inviteStatus: 'CONFIRMED',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: 'rJdDa8',
        price: '520',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '5ZZap5',
        price: '312',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '57PNxr',
        price: '187',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'roMz28',
        price: '416',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rD46gr',
        price: '249',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lvYpZr',
        price: '149',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8VBNg8',
        price: '416',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'ljKoB8',
        price: '249',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'r6LNB8',
        price: '149',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'lLjVB5',
        price: '52',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: '8Px9k8',
        price: '41',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '8g1dar',
        price: '26',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'l99NJl',
        price: '20',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: '8mq3j8',
    showId: null,
    username: null,
    name: '陈秋',
    sex: 'MALE',
    avatar:
      'https://staff-avatars-dev.oss-cn-beijing.aliyuncs.com/2f1d1976-041f-4a37-bae3-1aa09da20308',
    title: 'RESIDENT_PHYSICIAN',
    departmentName: '测试科室',
    tel: '18301009999',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'NORMAL',
    inviteStatus: 'CONFIRMED',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: '8K1b2r',
        price: '10000',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '5A7ewl',
        price: '6000',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '5bWd9r',
        price: '3600',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8Pk3ml',
        price: '800',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lLbzN5',
        price: '480',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8Ve4dl',
        price: '288',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rwabP8',
        price: '800',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'l9jGA8',
        price: '480',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8g7Lz8',
        price: '288',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'lOE4E5',
        price: '100',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'rq1Znr',
        price: '80',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: 'l1Naz8',
        price: '50',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: '5bWdkr',
        price: '40',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: '8nVxR8',
    showId: null,
    username: null,
    name: '刘大钊',
    sex: 'MALE',
    avatar: '',
    title: 'ATTENDING_PHYSICIAN',
    departmentName: null,
    tel: '18300009999',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'TO_REVIEW',
    inviteStatus: 'WAITING',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: 'ljYLjr',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '8VgeX5',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lLyb48',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8PBkjr',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '8gN74l',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'l9AjEl',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rwVak5',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lOpEb8',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rqz16l',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'l1PNdr',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: '5b4W9l',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '5AG7wl',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: '8KQ12r',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: 'rYkgO8',
    showId: null,
    username: null,
    name: '24r42354',
    sex: 'MALE',
    avatar: '',
    title: 'ATTENDING_PHYSICIAN',
    departmentName: null,
    tel: '15145454545',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'FAILURE',
    inviteStatus: 'WAITING',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: 'lOadw5',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rqMDEr',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'l1MYXl',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5bLZyl',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '5AV3qr',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8KAjVr',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8VdZmr',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lLKW6r',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8P4Zb8',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8gODp8',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'l9nYV8',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: 'rwXLBl',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'lOadq5',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: 'ldda4l',
    showId: null,
    username: null,
    name: 'dfdafa',
    sex: 'MALE',
    avatar: '',
    title: 'ATTENDING_PHYSICIAN',
    departmentName: null,
    tel: '13866666666',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'FAILURE',
    inviteStatus: 'WAITING',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: '8KAgVr',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lE94Nl',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rkAzg8',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5aVDor',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '54eDVr',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lMEw0l',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5RRAG5',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'lGORRl',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 're9jDr',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '8NkO65',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'ldgzGr',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: '8XYMn5',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'rYnRLl',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
  {
    id: 'lED29r',
    showId: null,
    username: null,
    name: '魂牵梦城',
    sex: 'MALE',
    avatar:
      'https://staff-avatars-dev.oss-cn-beijing.aliyuncs.com/04f08131-a0b3-4ca8-8e46-c5cb1a323567',
    title: 'ATTENDING_PHYSICIAN',
    departmentName: null,
    tel: '13455555555',
    expertise: null,
    biography: null,
    experience: null,
    certificates: null,
    roles: ['DOCTOR', 'ASSISTANT'],
    status: 'FAILURE',
    inviteStatus: 'WAITING',
    qrCodeUrl: null,
    meetingLecture: null,
    hospitalIntroduction: null,
    firstProfessionCompany: null,
    goodsDescriptions: [
      {
        goodsId: '8ynyj5',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: 'rzmpP5',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '8WXJL5',
        price: '0',
        category: 'INDEPENDENT_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rp4m4r',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '5BLWAl',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: 'r2R0yr',
        price: '0',
        category: 'SUPERIOR_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: '5040j5',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_YEAR',
        canModify: true,
      },
      {
        goodsId: '57XW1r',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_HALF_YEAR',
        canModify: true,
      },
      {
        goodsId: '5Zm3A8',
        price: '0',
        category: 'SUBORDINATE_VIP',
        type: 'VIP_QUARTER',
        canModify: true,
      },
      {
        goodsId: 'rJbmqr',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_12',
        canModify: true,
      },
      {
        goodsId: 'lvjmyl',
        price: '0',
        category: 'DOCTOR_CONSULTATION',
        type: 'CONSULTATION_24',
        canModify: true,
      },
      {
        goodsId: 'rDgWb5',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'VIDEO',
        canModify: true,
      },
      {
        goodsId: 'roaZ38',
        price: '0',
        category: 'MEDIA_SERVICE',
        type: 'AUDIO',
        canModify: true,
      },
    ],
    unAcceptEndTime: null,
    consultationAcceptStatus: null,
    workOrderAcceptStatus: null,
    departmentCategory: 'CARDIOVASCULAR',
    organizationId: 'olLDlK',
    bank: null,
    bankCardNumber: null,
    idNumber: null,
    inviterName: null,
    inviterTel: null,
    doctorGroup: null,
    doctorAttribute: null,
    firstProfessionCompanyLevel: null,
    qualificationCode: null,
    qualificationDate: null,
    practiceCode: null,
    practiceDate: null,
    wechatBindStatus: null,
    patientNum: 0,
  },
];
export default data;
