const rootData = {
  rootName: '杨毅民',
  downward: {
    direction: 'downward',
    name: '杨毅民',
    level: '总PI',
    firstProfessionCompany: '中国医学科学院北京协和医院',
    group: '多中心项目演示',
    amount: '100',
    ratio: '55%',
    hasHumanholding: true,
    hasChildren: true,
    isExpand: true,
    children: [
      {
        level: '分PI',
        name: '林志平',
        firstProfessionCompany: '国家心脏病中心阜外医院',
        group: '北京组',
        hasHumanholding: false,
        hasChildren: true,
        amount: '100',
        ratio: '55%',
        children: [
          {
            level: 'PI',
            name: '张韦水',
            firstProfessionCompany: '复旦大学附属华山医院',
            group: '西城区组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '宋轩天',
                firstProfessionCompany: '司济大学上海东方医院',
                group: '西城区组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
          {
            level: 'PI',
            name: '侯文贤',
            firstProfessionCompany: '上海交通大学附属第九人民医院',
            group: '东城区组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '魏得风',
                firstProfessionCompany: '郑州大学第一附属医院',
                group: '东城区组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
        ],
      },
      {
        level: '分PI',
        name: '林明春',
        firstProfessionCompany: '北京大学人民医院',
        group: '山东组',
        hasHumanholding: false,
        hasChildren: true,
        amount: '100',
        ratio: '55%',
        children: [
          {
            level: 'PI',
            name: '吴乃亚',
            firstProfessionCompany: '上海交通大学附属仁济医院',
            group: '济南组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '陈俊安',
                firstProfessionCompany: '山西白求恩医院',
                group: '济南组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  upward: {
    direction: 'downward',
    name: '杨毅民',
    level: '总PI',
    firstProfessionCompany: '中国医学科学院北京协和医院',
    group: '多中心项目演示',
    amount: '100',
    ratio: '55%',
    hasHumanholding: true,
    hasChildren: true,
    isExpand: true,
    children: [
      {
        level: '分PI',
        name: '林志平',
        firstProfessionCompany: '国家心脏病中心阜外医院',
        group: '北京组',
        hasHumanholding: false,
        hasChildren: true,
        amount: '100',
        ratio: '55%',
        children: [
          {
            level: 'PI',
            name: '张韦水',
            firstProfessionCompany: '复旦大学附属华山医院',
            group: '西城区组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '宋轩天',
                firstProfessionCompany: '司济大学上海东方医院',
                group: '西城区组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
          {
            level: 'PI',
            name: '侯文贤',
            firstProfessionCompany: '上海交通大学附属第九人民医院',
            group: '东城区组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '魏得风',
                firstProfessionCompany: '郑州大学第一附属医院',
                group: '东城区组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
        ],
      },
      {
        level: '分PI',
        name: '林明春',
        firstProfessionCompany: '北京大学人民医院',
        group: '山东组',
        hasHumanholding: false,
        hasChildren: true,
        amount: '100',
        ratio: '55%',
        children: [
          {
            level: 'PI',
            name: '吴乃亚',
            firstProfessionCompany: '上海交通大学附属仁济医院',
            group: '济南组',
            hasHumanholding: false,
            hasChildren: true,
            amount: '100',
            ratio: '55%',
            children: [
              {
                level: '研究者',
                name: '陈俊安',
                firstProfessionCompany: '山西白求恩医院',
                group: '济南组',
                hasHumanholding: false,
                hasChildren: false,
                amount: '100',
                ratio: '55%',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};

export default rootData;
